FROM python:3.7.3-stretch

## Step 1:
WORKDIR /app

## Step 2:
COPY . app.py /app/

## Step 3:
# Install packages from requirements.txt
RUN pip install  Click==7.0
RUN pip install Flask==1.0.2
RUN pip install itsdangerous==1.1.0
RUN pip install Jinja2==2.10.3
RUN pip install MarkupSafe==1.1.1
RUN pip install numpy==1.19.5
RUN pip install pandas==0.24.2
RUN pip install python-dateutil==2.8.0
RUN pip install pytz==2019.3
RUN pip install scikit-learn==0.20.3
RUN pip install scipy==1.3.1
RUN pip install six==1.12.0
RUN pip install Werkzeug==0.16.0
RUN pip install pylint==2.4.4

# hadolint ignore=DL3013

## Step 4:
EXPOSE 80

## Step 5:
# Run app.py at container launch
CMD ["python", "app.py"]
